version: '3.8'

services:
  php:
    image: php:8.3-fpm
    container_name: laravel_validate
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge


